### Recuperar todas las movies.
GET http://localhost:3000/movies

### Recuperar una movie por id.
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las movies por genero, en este caso se usa así porque genero solo lo utilizo como filtro.
GET http://localhost:3000/movies?genre=Action

### Crear una pelicula

POST http://localhost:3000/movies
Content-Type: application/json

{
    "id": "543534",
    "title": "Game of Thrones",
    "year": 2024,
    "director": "Christopher Nolan",
    "duration": 152,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "genre": [
      "Action",
      "Crime",
      "Drama"
    ],
    "rate": 9
  }

### Actualizar una pelicula.
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 1998,
    "title": "gsdgsdgsd"
}